name: Rambuid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Library External ---
  shared_preferences: ^2.2.2  # Penyimpanan Lokal
  intl: 0.20.2               # Format Tanggal
  provider: ^6.1.1
  permission_handler: ^11.3.1 # <--- TAMBAHKAN BARIS INI DI SINI
  curved_labeled_navigation_bar: ^2.0.6
  flutter_tts: ^3.8.3
  flutter_launcher_icons: ^0.14.2
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^11.0.1
  http: ^1.1.0
  url_launcher: ^6.2.5
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.0
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Konfigurasi Icon Aplikasi
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_rambuid.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_rambuid.png"

flutter:
  uses-material-design: true

  # Konfigurasi Aset
  assets:
    - assets/images/
    - assets/database/rambuid.db
    - assets/map/rambu_map.html


  # Konfigurasi Font
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700